DROP TABLE users CASCADE;
DROP TABLE teams CASCADE;
DROP TABLE players CASCADE;
DROP TABLE transfers CASCADE;
DROP TABLE transfer_listings CASCADE;

DROP TYPE listing_status CASCADE;
DROP TYPE player_position CASCADE;
